### ISSUE TITLE
feature request: Add JSHint violations

### ISSUE THREAD

**Issue by ilinkuo** [jenkinsci/violations-plugin#25]
JSHint is just a fork of JSLint. The output format is the same as JSLint, so it should be processed by the violations plugin in the same way. We're currently working around this by changing the name of the root element of the JSHint output from "JSHint" to "JSLint", and then pointing Violations to the modified JSHint output file. It would be nice if this were supported in Violations.

This feature can be added to the UI in several different ways:
* Add a new category for JSHint
* or, add a combined category for JSLint/JSHint
* or, add an Other category, where the user picks amongst formats such as JUnit, JSLint, etc.

The last one is most preferred.

**Comment by tomasbjerre** [comment]
@ilinkuo Can we close this issue? I am using JSHint with checkstyle format, works great for me. So I dont think its worth the time to implement this.
