### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gforcada** [jenkinsci/violations-plugin#61]
@mfriedenhagen I see that you made quite a few merges on this plugin, would it be possible to also make a release so that those fixes get into our jenkins servers?

If not, is there any instructions around to build and deploy jenkins plugins (for java newbies)?

**Comment by mfriedenhagen** [comment]
Hello Gil, I did develop some things in a branch, but they did not work out
properly for Maven 2 jobs. We now do use SonarQube for QA metrics instead
and did remove the violations plugin completely from our Jenkins
infrastructure.

Regards Mirko
-- 
http://illegalstateexception.blogspot.com/
https://github.com/mfriedenhagen/ (http://osrc.dfm.io/mfriedenhagen)
https://bitbucket.org/mfriedenhagen/

**Comment by tomasbjerre** [comment]
I am considering forking this repo and release it on my own. This plugin is not maintained properly!

I need the lib in maven repos ( https://github.com/jenkinsci/violations-plugin/issues/60 ) and getting tired of waiting for such a simple thing...

**Comment by tomasbjerre** [comment]
I'm having a discussion about this in Jenkins Developers mailing list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jenkinsci-dev/mWUgOZc61KY

**Comment by gforcada** [comment]
@tomasbjerre sounds really cool to me, I would actually do a first experimental release right away, so that we can already test if what's already in is working or not.

Unfortunately I don't have much time nor knowledge to help on this, but I have some time to test the releases

**Comment by tomasbjerre** [comment]
What do you think about https://github.com/jenkinsci/violations-plugin/pull/62 ? I would like to merge it and then start writing test cases and cleaning the code.

**Comment by mfriedenhagen** [comment]
The killer for this plugin was JENKINS-24506. There is still a branch here where I tried to fix it but did not succeed. So setting a build to unstable or failed is not possible with Maven2 jobs.

**Comment by mfriedenhagen** [comment]
The killer for this plugin was JENKINS-24506. There is still a branch here where I tried to fix it but did not succeed. So setting a build to unstable or failed is not possible with Maven2 jobs.

The other PR #6 is very, very old. I did not merge it because I used it in a private vendor version and forgot about it

**Comment by tomasbjerre** [comment]
You mean #4 not #6 right?
Can we close #6 if we cherry-pick these?
https://github.com/jenkinsci/violations-plugin/commit/0a15a05831a9711b04e4da558d6f87a027df9d61
https://github.com/jenkinsci/violations-plugin/commit/670cfca2cb68c378e347a538ee20cdebb9275f5b

Would also be nice to have your opinion on my suggested approach for a new release.

**Comment by tomasbjerre** [comment]
Sorry for spamming =) I was testing commits in Travis CI, so was pushing alot... should probably avoid having the issue in the comment next time.

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/violations-plugin/releases/tag/violations-0.8.0-alpha-1
