### ISSUE TITLE
sample files available for testing each parser ?

### ISSUE THREAD

**Issue by ryoichitaniguchi** [jenkinsci/violations-plugin#87]
Hello,
I internally planed to implement additional configuration "threshold". I expect that it can ignore low level violations than configured value. Currently, I somehow can test checkstyle or codenarc but the others,  not. its good to have xml file for test every function works only on post-build. 

appreciate if any reply, 
thank you

**Comment by ryoichitaniguchi** [comment]
hope someone complete this feature... partially implemented 616e855b6bb612ae1041f4afda2568d1e964a224
![threshold-violations-plugin](https://cloud.githubusercontent.com/assets/14815593/13278538/9a9ac380-db14-11e5-8198-133f5a37c1b6.png)

**Comment by tomasbjerre** [comment]
There are som esample files here:
https://github.com/jenkinsci/violations-plugin/tree/master/src/test/resources/hudson/plugins/violations/types

**Comment by ryoichitaniguchi** [comment]
Thank you for the information @tomasbjerre !
